language: node_js

node_js:
  - "4"
  - "0.12"
  - "0.10"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - node_js: "6"
  fast_finish: true

branches:
  except:
    - /^greenkeeper-.+$/
