language: node_js

node_js:
  - "4"
  - "0.12"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint

branches:
  except:
    - /^greenkeeper-.+$/

script:
  - if [ "$TEST_SUITE" == "lint" ]; then npm run lint; else npm run test:all; fi

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == "4" && "$TEST_SUITE" != "lint" ]]; then npm run coverage; fi
